import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import ThemeRegistry from "./ThemeRegistry";
import React from "react";
import { AppBar, Toolbar, Typography, Button, Box, Container } from "@mui/material";
import Link from "next/link";

const geistSans = Geist({ subsets: ["latin"], variable: "--font-geist-sans" });
const geistMono = Geist_Mono({ subsets: ["latin"], variable: "--font-geist-mono" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeRegistry>
          <AppBar position="static" color="primary" elevation={2} sx={{ mb: 4 }}>
            <Toolbar sx={{ display: 'flex', justifyContent: 'space-between' }}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
                <Typography variant="h6" component="div" sx={{ fontWeight: 700, letterSpacing: 1 }}>
                  🚀 Data Alchemist
                </Typography>
              </Box>
              <Box sx={{ display: 'flex', gap: 2 }}>
                <Link href="/" style={{ textDecoration: 'none' }}>
                  <Button color="inherit" sx={{ fontWeight: 500 }}>Main</Button>
                </Link>
                <Link href="/rules" style={{ textDecoration: 'none' }}>
                  <Button color="inherit" sx={{ fontWeight: 500 }}>Rules</Button>
                </Link>
                <Link href="/prioritization" style={{ textDecoration: 'none' }}>
                  <Button color="inherit" sx={{ fontWeight: 500 }}>Prioritization</Button>
                </Link>
              </Box>
            </Toolbar>
          </AppBar>
          <Container maxWidth="xl" sx={{ mt: 4, mb: 4 }}>
            {children}
          </Container>
        </ThemeRegistry>
      </body>
    </html>
  );
}
